ALTER TABLE wicket ADD COLUMN event int;
ALTER TABLE wicket ADD COLUMN bowler int;

ALTER TABLE wicket ADD CONSTRAINT fk_event FOREIGN KEY (event) REFERENCES event(id) ON DELETE CASCADE;
ALTER TABLE wicket ADD CONSTRAINT fk_bowler FOREIGN KEY (bowler) REFERENCES player(id) ON DELETE CASCADE;
